apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace = "com.termux.shared"

    compileSdk = project.properties.compileSdkVersion.toInteger()
    ndkVersion = System.getenv("JITPACK_NDK_VERSION") ?: project.properties.ndkVersion

    dependencies {
        implementation libs.androidx.appcompat
        implementation libs.androidx.annotation
        implementation libs.androidx.core
        implementation libs.androidx.recyclerview
        implementation libs.material
        implementation libs.commonmark

        // Do not increment version higher than 2.5 or there
        // will be runtime exceptions on android < 8
        // due to missing classes like java.nio.file.Path.

        implementation project(":terminal-view")

        implementation libs.termux.am.library
    }

    defaultConfig {
        minSdk = project.properties.minSdkVersion.toInteger()
        targetSdk = project.properties.targetSdkVersion.toInteger()
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            ndkBuild {
                cppFlags ''
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
            returnDefaultValues = true
        }
    }

    externalNativeBuild {
        ndkBuild {
            path file('src/main/cpp/Android.mk')
        }
    }

    publishing {
        multipleVariants {
            withSourcesJar()
            withJavadocJar()
            allVariants()
        }
    }
}

dependencies {
    testImplementation libs.junit
    testImplementation libs.robolectric
    androidTestImplementation libs.androidx.test.ext.junit

}

afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                from components.default
                groupId = 'com.termux'
                artifactId = 'termux-shared'
                version = '0.118.0'
            }
        }
    }
}
